### ISSUE TITLE
How is SION different from YAML and TOML?

### ISSUE THREAD

**Issue by KeitoTobi1** [dankogai/swift-sion#1]
どうも。日本語でIssueを出しています。

先日、なにかいいデータ交換フォーマットがないかを調べてみたら[PON](https://bitbucket.org/ruamel/pon/src/default/)というプロジェクトにたどり着きました。

……ですが、「他の言語でも使えますか？」と質問したら「このフォーマットはPython限定なので他の言語で使いたいのならYAMLに変換しろ」という回答が返ってきました。

でも、逆に言えば「YAML相当の性能を持つデータ交換フォーマット」だったら何でも変換できるということを知り、あれこれ調べたらこのプロジェクトが見つかりました。

そこで、[YAML](https://yaml.org/)や[TOML](https://github.com/toml-lang/toml)とこのSIONの違いを教えてくれないでしょうか？

**Comment by dankogai** [comment]
See:

* https://qiita.com/dankogai/items/a0b5005b3530a8e273da
* https://dankogai.github.io/SION/
