### ISSUE TITLE
.doubleでの整数値の取り扱いについて

### ISSUE THREAD

**Issue by kimtaedoo** [dankogai/swift-sion#3]
swift-sionを利用させていただいています。（以前も一度質問をさせていただきました）

先日、特定のデータを対象に処理を行うとアプリが落ちてしまう事象が発生しまして、問題箇所を確認したところ

>         sub.area_size = Float(json["area_size"].double!)

このようにして、 float 型でデータ処理を行う箇所があったのですが json["area_size"] に整数値（ 1 や 1.00 など ）が入力されていると、戻り値が nil になるようでnon-optionalにして ! をつけているとアプリが異常終了してしいました。

元々の事象発生は 1 という入力だったため、JSONデータ側を調整をしてみて、1.00 や "1.00" などのパターンも試してみましたが、データ側の調整では解消できませんでした。
小数点以下に何らかの値が入っていれば（1.05など）全く問題なく処理できています。

ひとまず

>        sub.area_size = Float(json["area_size"].double ?? Double(json["area_size"].int!))

このようにして、 .double が nil の場合は int から取り出すことで事象が回避できたのですが、整数値の取り扱いができなかったのは、なにかライブラリの使い方に問題があったのでしょうか？

**Comment by dankogai** [comment]
これが正しい挙動です。「整数を取り扱わない」のではなく「`Int`は`Double`ではない」という型が静的であるという話なので。このあたりが`Number`つまり`Double`しか数値型がないJSONと決定的に異なる点でもあります。

とはいえ需要があるのは理解できるので、別名のメソッドを `extention` で用意するのが良いかと。

```swift
extension SION {
    public var number:Double? {
      get {
        switch self {
          case .Double(let v):
            return v
          case .Int(let v):
            return Swift.Double(v) // Double だと SION.Double と区別がつかない
          default:
            return nil
          }
      }
   }
}
```

REPL
```shell
 15> SION(1).double 
$R0: Double? = nil
 16> SION(1).number
$R1: Double? = 1
 17> SION(1.0).double 
$R2: Double? = 1
 18> SION(1.0).number
$R3: Double? = 1
```

**Comment by dankogai** [comment]
Version [0.2.3] より `.number` を正式に追加しました。定義は上記の通りです。

[0.2.3]: https://github.com/dankogai/swift-sion/tree/0.2.3
